config/routes.rb
MallsDeals::Application.routes.draw do
  resources :malls

end

app/models/mall.rb
class Mall
  include Mongoid::Document
  field :name, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/malls_controller.rb
class MallsController < ApplicationController
  before_action :set_mall, only: [:show, :edit, :update, :destroy]

  # GET /malls
  def index
    @malls = Mall.all
  end

  # GET /malls/1
  def show
  end

  # GET /malls/new
  def new
    @mall = Mall.new
  end

  # GET /malls/1/edit
  def edit
  end

  # POST /malls
  def create
    @mall = Mall.new(mall_params)

    if @mall.save
      redirect_to @mall, notice: 'Mall was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /malls/1
  def update
    if @mall.update(mall_params)
      redirect_to @mall, notice: 'Mall was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /malls/1
  def destroy
    @mall.destroy
    redirect_to malls_url, notice: 'Mall was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mall
      @mall = Mall.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def mall_params
      params.require(:mall).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/malls_helper.rb
module MallsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MallsDeals</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/malls/_form.html.erb
<%= form_for(@mall) do |f| %>
  <% if @mall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mall.errors.count, "error") %> prohibited this mall from being saved:</h2>

      <ul>
      <% @mall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/malls/edit.html.erb
<h1>Editing Mall</h1>

<%= render 'form' %>

<%= link_to 'Show', @mall %> |
<%= link_to 'Back', malls_path %>

app/views/malls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Malls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @malls.each do |mall| %>
      <tr>
        <td><%= mall.name %></td>
        <td><%= link_to 'Show', mall %></td>
        <td><%= link_to 'Edit', edit_mall_path(mall) %></td>
        <td><%= link_to 'Destroy', mall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mall', new_mall_path %>

app/views/malls/new.html.erb
<h1>New Mall</h1>

<%= render 'form' %>

<%= link_to 'Back', malls_path %>

app/views/malls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mall.name %>
</p>

<%= link_to 'Edit', edit_mall_path(@mall) %> |
<%= link_to 'Back', malls_path %>